### ISSUE TITLE
Add PHP 8.0 Support

### ISSUE THREAD

**Issue by romulus-ai** [Icinga/docker-icingaweb2#100]
Since a Icinga supports since 2.9.0 PHP 8, it would be nice to add support for it. This Release is available since Juli 2021.

A few Addons for Icinga Web are already only support PHP 8, so it would be really nice to have PHP 8.0 as a base for Icinga Web.

**Comment by Al2Klimov** [comment]
This will come with Debian 12 once we update the base image.

**Comment by romulus-ai** [comment]
Ok, thanks, then we have to build it on our own.. It takes to much time until debian 12 is ready..

**Comment by Caprico85** [comment]
Debian 12 is out for quite a while now. Will the image see an update?

**Comment by Al2Klimov** [comment]
* Indeed we plan to #116
