### ISSUE TITLE
mysql.schema.sql missing in 2.11.4

### ISSUE THREAD

**Issue by andrewleech** [Icinga/docker-icingaweb2#110]
I was setting up a new installation based on the docker-compose configuration as per: https://icinga.com/blog/2020/08/06/docker-compose-icinga and https://github.com/lippserd/docker-compose-icinga

Icingaweb fails to start with the docker logs:
```
ERROR: RuntimeException in /usr/share/icingaweb2/library/Icinga/Util/File.php:39 with message: SplFileObject::__construct(/usr/share/icingaweb2/etc/schema/mysql.schema.sql): failed to open stream: No such file or directory
```

I found the same issue reported in: https://community.icinga.com/t/sorry-failed-to-set-up-icinga-web-2-successfully/2448/13

Updating the docker-compose yaml to pin to 2.11.3 has worked around this issue for me currently.

**Comment by Al2Klimov** [comment]
Fixed by #108
