### ISSUE TITLE
Docker Image is updates to Debian12 PHP 8.2

### ISSUE THREAD

**Issue by Addi995** [Icinga/docker-icingaweb2#128]
Hi there, 

the Docker Image pushed to Docker Hub with Tag 2.12.1, 2.12 and 2 - 5 days ago is build with Debian bookworm and PHP 8.2

The main Image Tag is build with Debian bullseye and PHP 7.4. 

I dont think that this is correct. 

![grafik](https://github.com/user-attachments/assets/5f584e84-1ad9-4d6c-8c83-dc5b19125295)

**Comment by julianbrost** [comment]
@Al2Klimov I think that's a question for you: https://github.com/Icinga/docker-icingaweb2/pull/116#issuecomment-2377202025
