### ISSUE TITLE
Provide version freeze using tags

### ISSUE THREAD

**Issue by damoun** [Icinga/docker-icingaweb2#15]
Hi,

It would be great if you can provide icingaweb2 version by using docker tags.
Right now, only master is available so I cannot use it as my icinga2 version is not the last one.

Thanks

**Comment by Al2Klimov** [comment]
Hi,

we're already [discussing this](https://github.com/Icinga/icinga2/pull/8147#issuecomment-668093626) for v2.8.2+.

Best,
AK

**Comment by nilmerg** [comment]
hum? what's this about?

**Comment by Al2Klimov** [comment]
Please see my link. It's all about having those steps in Icinga Web 2, too.

**Comment by nilmerg** [comment]
Then I'd suggest to open a pull request there?

**Comment by Al2Klimov** [comment]
* [x] https://github.com/Icinga/icingaweb2/pull/4221

**Comment by Al2Klimov** [comment]
Should be there w/ v2.9.0.
