### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/docker-icingaweb2#2]
... in one volume.

**Comment by Al2Klimov** [comment]
@lippserd What else beyond /etc/icingaweb2 we need to persist by default? Sessions?

**Comment by lippserd** [comment]
> @lippserd What else beyond /etc/icingaweb2 we need to persist by default? Sessions?

Nothing else. Sessions also get destroyed if you reboot your machine running Web.
