### ISSUE TITLE
Icingaweb Director Module

### ISSUE THREAD

**Issue by opencommits** [Icinga/docker-icingaweb2#27]
Hi, 

first thanks for this great project! 👍 
 
It would be very nice, if the Icingaweb Module Director can be used in this Image. This is not possible out of the box at the moment:

![grafik](https://user-images.githubusercontent.com/54305643/99675031-051a0c00-2a77-11eb-94d6-a1787cf10c9d.png)

Can you update these modules in this Image provided at the DockerHub? https://hub.docker.com/r/icinga/icingaweb2

Thank you very much.

**Comment by nilmerg** [comment]
Hi,

I don't quite understand the problem you're having. The modules in question seem all installed in your container. Once you enabled them (just like you have to enable the director) this message should go away.

**Comment by opencommits** [comment]
You are right. Sorry, for that. 

Thank you for your work on this project :)
