### ISSUE TITLE
No tagged versions on Docker Hub available

### ISSUE THREAD

**Issue by mcktr** [Icinga/docker-icingaweb2#35]
Hi,

please provide tagged versions on Docker Hub for Icinga Web 2, following the released version of Icinga Web 2 e.g.:

- 2.8.2
- 2.7.4
- etc.

Currently there is only a `master` and `database-configuration-backend-3770` tag, which I consider not suitable for production environments. 

https://hub.docker.com/r/icinga/icingaweb2/tags

Best regards
Michael

**Comment by Al2Klimov** [comment]
Dup of https://github.com/Icinga/icingaweb2/issues/4294
