### ISSUE TITLE
Error: Class 'ipl\\I18n\\GettextTranslator' not found

### ISSUE THREAD

**Issue by dirkreitz** [Icinga/docker-icingaweb2#41]
The container is constantly restarting ...

{"log":"PHP Fatal error:  Uncaught Error: Class 'ipl\\I18n\\GettextTranslator' not found in /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootst
rap.php:710\n","stream":"stderr","time":"2021-06-08T11:32:06.940588098Z"}
{"log":"Stack trace:\n","stream":"stderr","time":"2021-06-08T11:32:06.9406087Z"}
{"log":"#0 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(44): Icinga\\Application\\ApplicationBootstrap-\u003eprepareInternationalization()\n","str
eam":"stderr","time":"2021-06-08T11:32:06.940612701Z"}
{"log":"#1 /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootstrap.php(416): Icinga\\Application\\Cli-\u003ebootstrap()\n","stream":"stderr","ti
me":"2021-06-08T11:32:06.940617201Z"}
{"log":"#2 /usr/share/icingaweb2/bin/icingacli(7): Icinga\\Application\\ApplicationBootstrap::start()\n","stream":"stderr","time":"2021-06-08T11:32:06.9406278
03Z"}
{"log":"#3 {main}\n","stream":"stderr","time":"2021-06-08T11:32:06.940632503Z"}
{"log":"  thrown in /usr/share/icingaweb2/library/Icinga/Application/ApplicationBootstrap.php on line 710\n","stream":"stderr","time":"2021-06-08T11:32:06.940
635703Z"}
{"log":"[Tue Jun 8 11:32:06.945395132 2021] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 255\n","stream":"stderr","time":"2021-06-08T11:32:06.9454925
43Z"}

Docker version 20.10.7, build f0df350 on Ubuntu 20.04-LTS running official docker-compose.yml by Eric Lippmann

**Comment by Al2Klimov** [comment]
@nilmerg Please could you do me a favour and inform me/Noah once IW2 v2.9 is **feature-complete, but not tagged yet** and all deps are **tagged**? So we can make sure the v2.9 tag will build a working Docker image.

**Comment by nilmerg** [comment]
There's now a latest, 2.8 and 2.8.2 tag. Please use either instead.

**Comment by nilmerg** [comment]
> Please could you do me a favour and inform me/Noah once IW2 v2.9 is feature-complete, but not tagged yet and all deps are tagged? So we can make sure the v2.9 tag will build a working Docker image.

I've created #42 for that. Will update this once tags are available.

**Comment by Al2Klimov** [comment]
> @nilmerg Please could you do me a favour and inform me/Noah once IW2 v2.9 is **feature-complete, but not tagged yet** and all deps are **tagged**? So we can make sure the v2.9 tag will build a working Docker image.

Or – better: Icinga/icingaweb2#4389

**Comment by dirkreitz** [comment]
I still get above mentioned error, altough I kicked out the old images (icinga/icinga2 and icinga/icingaweb2) and used the new ones created a few hours ago ...

**Comment by nilmerg** [comment]
The `master` tag still has this, yes. The other tags however don't have it, just checked it to make sure that's the case. Make sure you use the `latest` tag to create your own image, and remove all traces of it beforehand.

**Comment by dirkreitz** [comment]
I didn't made my own images, I just used Eric Lippmanns docker-compose.yml file and pulled the images from docker-hub.
But in fact changing the docker-compose file to 'image: icinga/icingaweb2:latest' seems to have solved the issue !

**Comment by nilmerg** [comment]
Do you have a link to that docker-compose.yml?

**Comment by dirkreitz** [comment]
Here you are ...
https://github.com/lippserd/docker-compose-icinga taken from https://icinga.com/blog/2020/08/06/docker-compose-icinga/

**Comment by nilmerg** [comment]
Ah, that one. Then I'd suggest to open a issue there to get the docker-compose.yml changed :wink:

**Comment by dirkreitz** [comment]
I will do so ...
