### ISSUE TITLE
ipl and reactbundle are now libraries and core dependencies

### ISSUE THREAD

**Issue by nilmerg** [Icinga/docker-icingaweb2#42]
The modules `icingaweb2-module-ipl` and `icingaweb2-module-reactbundle` are not supported anymore by the current master.

Instead it requires the following libraries:

* https://github.com/Icinga/icinga-php-library
* https://github.com/Icinga/icinga-php-thirdparty

None of those have a tag yet, but both have a `nightly/` branch which is usable.

They need to go to this location and are available for use instantly: `/usr/share/icinga-php`

Used directories don't really matter, but packages will use `/usr/share/icinga-php/ipl` and `/usr/share/icinga-php/vendor`.

I'd love to see that those are integrated into the current `master` build using their nightly branch.

**Comment by dwt** [comment]
Running against this right now - is there any way I can help make this happen?

**Comment by dwt** [comment]
Thanks! I'll check this out soon.

**Comment by dwt** [comment]
Not quite sure if I'm maybe doing something wrong, but with current docker images I still get lots of errors:

Left Sidebar:
```
Fatal error: Declaration of Icinga\Module\Icingadb\Model\Behavior\ReRoute::rewriteCondition(Icinga\Data\Filter\FilterExpression $expression, $relation = NULL) must be compatible with ipl\Orm\Contract\RewriteFilterBehavior::rewriteCondition(ipl\Stdlib\Filter\Condition $condition, $relation = NULL) in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Model/Behavior/ReRoute.php on line 10
```

Main Area, all the widgets:
```
Uncaught TypeError: Argument 1 passed to ipl\Orm\Compat\FilterProcessor::apply() must be an instance of ipl\Stdlib\Filter\Rule, instance of Icinga\Data\Filter\FilterAnd given, called in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php on line 263 and defined in /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Compat/FilterProcessor.php:33
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(263): ipl\Orm\Compat\FilterProcessor::apply(Object(Icinga\Data\Filter\FilterAnd), Object(ipl\Orm\Query))
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(245): Icinga\Module\Icingadb\Web\Controller->applyMonitoringRestriction(Object(ipl\Orm\Query))
#2 /usr/share/icingaweb2/modules/icingadb/application/controllers/ServicesController.php(67): Icinga\Module\Icingadb\Web\Controller->filter(Object(ipl\Orm\Query))
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(218): Icinga\Module\Icingadb\Controllers\ServicesCo
```

Do I need to do anything else besides update the images and trash the mysql /redis databases to make this work?
