### ISSUE TITLE
How to integrate this with ldap?

### ISSUE THREAD

**Issue by evollution** [Icinga/docker-icingaweb2#43]
Hi Team, right now i adapted icingaweb configuration to log in via LDAP and this is the error I get:

`PHP Fatal error:  Uncaught Error: Call to undefined method Icinga\Authentication\User\LdapUserBackend::insert() in /entrypoint-db-init/application/clicommands/DbCommand.php:71
Stack trace:
#0 /usr/share/icingaweb2/library/Icinga/Cli/Loader.php(265): Icinga\Module\Dockerentrypoint\Clicommands\DbCommand->userAction()
#1 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(162): Icinga\Cli\Loader->dispatch()
#2 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(152): Icinga\Application\Cli->dispatchOnce()
#3 /usr/share/icingaweb2/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /entrypoint-db-init/application/clicommands/DbCommand.php on line 71

Fatal error: Uncaught Error: Call to undefined method Icinga\Authentication\User\LdapUserBackend::insert() in /entrypoint-db-init/application/clicommands/DbCommand.php:71
Stack trace:
#0 /usr/share/icingaweb2/library/Icinga/Cli/Loader.php(265): Icinga\Module\Dockerentrypoint\Clicommands\DbCommand->userAction()
#1 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(162): Icinga\Cli\Loader->dispatch()
#2 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(152): Icinga\Application\Cli->dispatchOnce()
#3 /usr/share/icingaweb2/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /entrypoint-db-init/application/clicommands/DbCommand.php on line 71`

**Comment by evollution** [comment]
how should i configure this in order to work properly

**Comment by Al2Klimov** [comment]
Hello @evollution!

Did you set any env vars like `icingaweb.passwords.backend.user=pass`?

Best,
AK
