### ISSUE TITLE
Auto-migrate more recent preferences INI->DB

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/docker-icingaweb2#52]
I.e. on each start if preferences are stored in the database, compare timestamps of the existing INI ones to the ones in the DB.

* Nothing in INI? Good.
* INI > DB? Move.
* DB > INI? Discard INI.

All of the above per user of course.

**Comment by Al2Klimov** [comment]
What’s your opinion on this?

Before you ask: no, I’m going to use your new CLI command only as blueprint.

**Comment by lippserd** [comment]
Why do you even want to do this? Using a newer Docker image version also requires reading our upgrading documentation. If we migrate here automatically, we would have to document this here and in Web. Apart from that, I would also try to avoid deleting any data. After all, this is a volume that could also be used in other containers. So, users should have to migrate here themselves as well.

**Comment by Al2Klimov** [comment]
Aren’t Docker Images in general well-known for migrating everything automagically?

**Comment by lippserd** [comment]
I'd rather have something in Web where new versions of Web and modules register migrations that the user either manually initiates or, if we have an application daemon, run automatically.

**Comment by Al2Klimov** [comment]
Sounds like a plan.
