### ISSUE TITLE
Pages seems to be in acessibility mode.

### ISSUE THREAD

**Issue by tjapa** [Icinga/docker-icingaweb2#53]
## Describe the bug
Pages seems to be in acessibility mode.

## To Reproduce
Dockerfile to build image:

```
FROM alpine/git
WORKDIR /
RUN git clone https://github.com/Icinga/icingadb-web.git icingadb

FROM icinga/icingaweb2:2.9.3
USER root
RUN rm -rf /usr/share/icingaweb2/modules/icingadb/*
USER www-data
COPY --from=0 /icingadb /usr/share/icingaweb2/modules/icingadb
```

## Screenshots
![image](https://user-images.githubusercontent.com/17579637/130671550-adb7bf08-1d05-4751-8678-621b6e6912fa.png)

## Your Environment
Icinga Web 2 Version
2.9.3
Git commit
c757a17530c326c7d6daebd6171486cb8167a8a1
PHP Version
7.3.29-1~deb10u1
Git commit date
Loaded Libraries
Name	Version
icinga/icinga-php-thirdparty	0.10.0
icinga/icinga-php-library	0.6.1
Loaded Modules
Name	Version
icingadb	1.0.0-rc1

**Comment by Al2Klimov** [comment]
Share the thoughts you had while transferring this issue.

**Comment by nilmerg** [comment]
It's related to the docker image and how it's used.

**Comment by Al2Klimov** [comment]
You've missed some dependencies. Disable the Icinga DB mod via `docker exec` and `icingacli mod dis icingadb`. Try to re-enable it via the web interface to see which dependencies are missing.

**Comment by tjapa** [comment]
I did what you said. Now I get the message: "Module "ipl" is not enabled. This module is mandatory for Icinga DB Web".
The ipl module doesn't appear as a option in modules page.

Repeating the same process, but now with the module "ipl" enable via docker (which I think is wrong since it became the Icinga PHP Library), I get the last 2 screenshots.

# Screenshots
![image](https://user-images.githubusercontent.com/17579637/130969951-e5bf0ba8-472e-4156-86af-77c16db787ea.png)
![image](https://user-images.githubusercontent.com/17579637/130970023-2b974bab-ff7b-48ef-822d-792324fc07cf.png)
![image](https://user-images.githubusercontent.com/17579637/130970072-f42f312d-1971-40ca-9e62-06df5d086adb.png)

# Screenshots Test
![image](https://user-images.githubusercontent.com/17579637/130983643-0c06f35a-7118-4c5b-be15-f0114d6676d1.png)
![image](https://user-images.githubusercontent.com/17579637/130971237-bb71df5f-8a0f-484b-b4f5-1784b2740d8b.png)

**Comment by Al2Klimov** [comment]
What if you use not 2.9.3, but master as base?

**Comment by tjapa** [comment]
Ignore the last reply and screenshots, I was using the wrong Dockerfile, sorry. The problem using 2.9.3 and master are the same from the start.
Now the screenshoots are correctly. The last 2 screenshots with each docker image are the immediate result after enabling the icingadb module:

# Screenshots - 2.9.3
![image](https://user-images.githubusercontent.com/17579637/130991273-c2b9c4e6-e876-4fa1-9d30-a066ffc8c9a4.png)
![image](https://user-images.githubusercontent.com/17579637/130991315-a23a900a-437a-4e7b-9144-e333d9bb2e84.png)
![image](https://user-images.githubusercontent.com/17579637/130991348-f16a31d0-3ed7-46e2-a677-2e021d48bf64.png)
![image](https://user-images.githubusercontent.com/17579637/130991395-597a93d6-966d-4cbe-9100-3767d9023389.png)
![image](https://user-images.githubusercontent.com/17579637/130991430-4012872b-b846-4767-8ae1-4c9dc60d9851.png)

# Screenshots - Master
![image](https://user-images.githubusercontent.com/17579637/130990345-02af9d95-844c-41ae-b956-0e541035ae35.png)
![image](https://user-images.githubusercontent.com/17579637/130990444-c5b34865-0f8b-4ea7-9b79-5134a9321b18.png)
![image](https://user-images.githubusercontent.com/17579637/130990523-ec577a66-c477-4d43-9975-6aa6bce3deef.png)
![image](https://user-images.githubusercontent.com/17579637/130990555-c872a236-ed68-48d1-8c45-10ed7af2fe5c.png)
![image](https://user-images.githubusercontent.com/17579637/130990917-f4c14069-8160-4bd5-85dc-d8fb6c09000f.png)

**Comment by Al2Klimov** [comment]
Are there any PHP exceptions in the container log?

**Comment by tjapa** [comment]
I disabled the monitoring module to not get the errors saying that the backend was not configured, so I managed to catch this error:
```
[Thu Aug 26 15:54:18.460553 2021] [php7:error] [pid 17] [client 172.16.0.67:57618] PHP Fatal error:  Uncaught Less_Exception_Compiler: .card is undefined in anonymous-file-0.less in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Mixin/Call.php:143\nStack trace:\n#0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(143): Less_Tree_Mixin_Call->compile(Object(Less_Environment))\n#1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(86): Less_Tree_Ruleset->EvalMixinCalls(Object(Less_Tree_Ruleset), Object(Less_Environment), 4)\n#2 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile(Object(Less_Environment))\n#3 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile(Object(Less_Environment))\n#4 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(185): Less_Tree_Ruleset->compile(Object(Less_Environment))\n#5 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(130): Less_Parser->getCss()\n#6 /usr/share/icingaweb2/library/Icinga/Web/LessCompiler.php(272): in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Mixin/Call.php on line 143, referer: http://172.16.0.135:8080/dashboard
```

**Comment by Al2Klimov** [comment]
@nilmerg Has the monitoring mod to actually be enabled?

**Comment by nilmerg** [comment]
Not for Icinga DB Web master. `.card is undefined` is due to ipl-web being outdated. Isn't the master tag using the master/main branch everywhere?

**Comment by Al2Klimov** [comment]
Anyway:

@tjapa An upcoming Docker image will include the upcoming Icinga DB RC2/final. I consider waiting for it much easier.

**Comment by tjapa** [comment]
I understood. I will wait. Thank you very much.

**Comment by dwt** [comment]
@Al2Klimov I've just tried with master and it still seems to be waiting for rc2/final - any timeline when this can be tried again?

**Comment by dwt** [comment]
It seems that #58 might be the fix for these problems? If so, please comment.

**Comment by julianbrost** [comment]
Once the next `icinga/icingaweb2:master` image is pushed to Docker Hub (should happen tonight), that should include a working version of the current `icingadb-web@master`.

The Dockerfile in the first post of this issue still won't work, but that's because the version of `icinga-php-library` that's in `icinga/icingaweb2:2.9.3` is not compatible with `icingadb-web@master`, so this mixes modules in incompatible versions. It might work when also updating `icinga-php-library`, but I'm not sure if that's all, there could be other incompatibilities.

**Comment by dwt** [comment]
@julianbrost I'm on this docker compose file: https://github.com/dwt/docker-compose-icinga, any info on required changes would be quite appreciated.

**Comment by julianbrost** [comment]
Hm, seems like the `icinga/icingaweb2:master` image on Docker Hub still uses the broken version combination. I'll try to get that fixed, for now you should be able to build a working image for youself by doing:
```
git clone https://github.com/Icinga/docker-icingaweb2.git
git clone https://github.com/Icinga/icingaweb2.git
cd docker-icingaweb2
./build.bash ../icingaweb2 master
```
