### ISSUE TITLE
Starting Image plasters error messages all over the UI

### ISSUE THREAD

**Issue by dwt** [Icinga/docker-icingaweb2#59]
Hi there,

starting the current image plasters error messages like this all over the ui:

```
Declaration of Icinga\Module\Icingadb\Model\Behavior\ReRoute::rewriteCondition(Icinga\Data\Filter\FilterExpression $expression, $relation = NULL) must be compatible with ipl\Orm\Contract\RewriteFilterBehavior::rewriteCondition(ipl\Stdlib\Filter\Condition $condition, $relation = NULL) in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Model/Behavior/ReRoute.php on line 10
```

```
Uncaught TypeError: Argument 1 passed to ipl\Orm\Compat\FilterProcessor::apply() must be an instance of ipl\Stdlib\Filter\Rule, instance of Icinga\Data\Filter\FilterAnd given, called in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php on line 263 and defined in /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Compat/FilterProcessor.php:33
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(263): ipl\Orm\Compat\FilterProcessor::apply(Object(Icinga\Data\Filter\FilterAnd), Object(ipl\Orm\Query))
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(245): Icinga\Module\Icingadb\Web\Controller->applyMonitoringRestriction(Object(ipl\Orm\Query))
#2 /usr/share/icingaweb2/modules/icingadb/application/controllers/ServicesController.php(67): Icinga\Module\Icingadb\Web\Controller->filter(Object(ipl\Orm\Query))
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(218): Icinga\Module\Icingadb\Controllers\ServicesCo

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

I can get rid of these error messages by removing the file /etc/icingaweb2/enabledModules/ipl from the container, but it is re-created from the container init script, so it seems as if it's there on purpose.

This is with the current icinga/icingaweb2:master image.

Any input?

**Comment by dwt** [comment]
It looks a lot like the errors supposedly caused / fixed by https://github.com/Icinga/docker-icingaweb2/issues/46 - is there some more migration work I need to do on my side?

What I tried: removing all containers, volumes and networks from docker, then removing the mapped files and then restarting the container.

**Comment by dwt** [comment]
ping? Is there anything I'm doing wrong? Should I spend more time debugging this? Is this a known issue?

**Comment by dwt** [comment]
Retrying this with the docker images that are current right now this problem is no longer reproducible.

**Comment by lippserd** [comment]
> Retrying this with the docker images that are current right now this problem is no longer reproducible.

Thanks for the feedback. We were in the process of changing repos left and right for the RC2 release at the time, so this was broken for a couple of days.

**Comment by dwt** [comment]
Well, it certainly halted my transition from icinga1 to icinga2 by a couple of months. :-( Here's hope that the master branches will be more stable going forward and / or are released soon!
