### ISSUE TITLE
Has the configuration for the redis database changed?

### ISSUE THREAD

**Issue by dwt** [Icinga/docker-icingaweb2#65]
Right now the documented way to configure the redis database to use is [per readme](https://github.com/Icinga/docker-icingaweb2/blob/356295aefc32ae4e5b994cc47390d4244a640e54/README.md?plain=1#L23)

to set 
```
      icingaweb.modules.icingadb.config.redis1.host: redis
      icingaweb.modules.icingadb.config.redis1.port: 6379
```

however, I needed this config to make it work for me:
```
      icingaweb.modules.icingadb.redis.redis1.host: redis
      icingaweb.modules.icingadb.redis.redis1.port: 6379
```

Is that a bug in icingaweb, icingaweb-docker or the documentation?

**Comment by lippserd** [comment]
Hi,

The documentation is outdated. Thanks for report!

All the best,
Eric

**Comment by dwt** [comment]
In a very similar manner, according to the readme this configuration sets sets up the api user:

```
      icingaweb.modules.monitoring.commandtransports.icinga2.transport: api
      icingaweb.modules.monitoring.commandtransports.icinga2.host: icinga2
      icingaweb.modules.monitoring.commandtransports.icinga2.username: icingaweb
      icingaweb.modules.monitoring.commandtransports.icinga2.password: ${ICINGAWEB_ICINGA2_API_USER_PASSWORD}
```

However I needed
```
      icingaweb.modules.icingadb.commandtransports.icinga2.transport: api
      icingaweb.modules.icingadb.commandtransports.icinga2.host: icinga2
      icingaweb.modules.icingadb.commandtransports.icinga2.port: 5665
      icingaweb.modules.icingadb.commandtransports.icinga2.username: icingaweb
      icingaweb.modules.icingadb.commandtransports.icinga2.password: ${ICINGAWEB_ICINGA2_API_USER_PASSWORD}
```

Is this the same issue?

**Comment by dwt** [comment]
@lippserd @Al2Klimov ping - this seems like an easy fix, are you guys waiting for a pull request for this? (I'd be happy to provide one).

**Comment by Al2Klimov** [comment]
You have green light.

**Comment by dwt** [comment]
🎉
