### ISSUE TITLE
Director Background Daemon not running

### ISSUE THREAD

**Issue by weedpump** [Icinga/docker-icingaweb2#71]
Unfortunately, the director background daemon is not started automatically.

I can start it manually by executing "docker exec <container> icingacli director daemon run".

Is it possible to run the director daemon on startup or do you have any suggestions, how to achieve this?

**Comment by Al2Klimov** [comment]
Hello,

have you tried a separate container with the same volumes and `icingacli director daemon run`?

**Comment by weedpump** [comment]
That works, thank you!
