### ISSUE TITLE
Possibility to add more modules

### ISSUE THREAD

**Issue by verboEse** [Icinga/docker-icingaweb2#76]
Hi.

I can't see a simple way with this image to add more modules to this setup. E. g. I would like to use Grafana instead of graphite. There are even more modules. Isn't there a way to integrate modules more dynamically?

**Comment by julianbrost** [comment]
Maybe this blog post I wrote a few months ago helps: https://icinga.com/blog/2021/10/20/installing-additional-modules-in-the-icinga-web-2-docker-container/

**Comment by verboEse** [comment]
Oh, didn't see that.
I like the approach with environment variable `icingaweb.config.global.module_path` :-)
Thanks for the hint!
