### ISSUE TITLE
IcingaDB Postgre question

### ISSUE THREAD

**Issue by kajla** [Icinga/docker-icingaweb2#80]
Hello,

I read that IcingaDB already supports PostgreSQL (here: https://icinga.com/docs/icinga-db/latest/doc/02-Installation/), but IcingaDB in Icingaweb2 2.10 image didn't support it.
Only MySQL available:
![only-mysql-available](https://user-images.githubusercontent.com/5457824/161260021-e5026f06-995d-405d-a842-f2bfda9e1195.png)

Used image:
```
# docker image ls
REPOSITORY          TAG       IMAGE ID       CREATED      SIZE
icinga/icingaweb2   2.10.0    22bf9a22d7b9   9 days ago   615MB
```
Could you help me, please?
Thank you in advance.

Best regards,
Adam

**Comment by julianbrost** [comment]
For the web interface, PostgreSQL support is still work in progress: https://github.com/Icinga/icingadb-web/pull/508
