### ISSUE TITLE
External auth usage

### ISSUE THREAD

**Issue by kajla** [Icinga/docker-icingaweb2#81]
Hello,

We plan to migrate to container version of Icingaweb2. Previously we used Apache2 OpenIDC module to auth in Icingaweb2. We have an external auth option during installation but now we can't configure apache for openidc module. 
Documentation: https://icinga.com/docs/icinga-web-2/latest/doc/05-Authentication/#external-authentication
Maybe there is a description of how this should be used now?
Or, is it a good idea to put a configured Apache in front of it?

Thank you in advance.

Best regards,
Adam

**Comment by julianbrost** [comment]
> Or, is it a good idea to put a configured Apache in front of it?

I think that's the way to go.

The container uses the Apache httpd internally and in theory you could use our images as base for your own images including additional modules and configuration, but that doesn't sound like something we can officially provide support for. There's just too many options how you could want to configure Apache.

Also, using another container as reverse proxy in front avoids having to build your image with every Icinga Web 2 update in contrast to just having to pull a new version of the image.
