### ISSUE TITLE
CSS corrupt in docker image tags 2/latest (all with digest: f565dab35996)

### ISSUE THREAD

**Issue by t0mcat1337** [Icinga/docker-icingaweb2#83]
Just tried out this icingaweb2 docker image. After starting it I opened the Login Screen which looks like this:

![grafik](https://user-images.githubusercontent.com/3826246/165486597-a063d29b-848c-49e7-9309-7948d5515bcf.png)

So obviously the CSS is corrupt, verifyable in the DevTools:
![grafik](https://user-images.githubusercontent.com/3826246/165487681-d7a8f6be-8d65-4ce7-8382-6154998d9d01.png)

The only working tag right now seems to be "master" (digest c1dd496b4dfe at the time of writing).

So following the docs on Docker Hub (or readme.md here) which are using the "latest" tag is ending in a corrupt icingaweb2 installation.

**Comment by Al2Klimov** [comment]
@nilmerg Any idea?

**Comment by nilmerg** [comment]
@Al2Klimov Maybe take a look at when all the other tags were created and when the master tag got fixed by #79??

**Comment by julianbrost** [comment]
#79 shouldn't make a different for release versions and indeed, I just rebuilt 2.10.1 locally and I experience the same problem.

Version information according to the image I built if that helps to figure out any incompatibilities:

Icinga Web 2 Version 	2.10.1
Git commit 	974729a6421c17fdb8bb1931623107cf6a90fc7e
PHP Version 	7.4.25
Git commit date 	2022-04-06

Loaded Libraries
icinga/icinga-php-library 	0.8.1
icinga/icinga-php-thirdparty 	0.10.0

Loaded Modules
icingadb 		1.0.0-rc2
monitoring 		2.10.1

**Comment by julianbrost** [comment]
Okay, so disabling the icingadb module fixes the issue. Looks like the latest tagged version is incompatible.

**Comment by lippserd** [comment]
Fixed.
