### ISSUE TITLE
Change configurable environment variables to 'traditional' syntax

### ISSUE THREAD

**Issue by mocdaniel** [Icinga/docker-icingaweb2#92]
Currently, the environment variables configurable for the docker-icingaweb2 image come with a syntax like `path.to.subcategory.setting` - this can be problematic for other tools which try to parse a more 'traditional' env syntax like `PATH_TO_SUBCATEGORY_SETTING`, e.g. [Acorn](https://acorn.io).

Is there a good reason for this unusual naming convention? Would it be possible to use the more traditional and in my eyes conventional style?

**Comment by Al2Klimov** [comment]
No problem! You wanna separate with _s, not .s – just do it. At your option. (Per env var.)

**Comment by Al2Klimov** [comment]
But you seem to have to write everything lower-case, is this OK?
