### ISSUE TITLE
./build.bash ./icingaweb2 issue

### ISSUE THREAD

**Issue by johnfelipe** [Icinga/docker-icingaweb2#97]
```
Step 13/13 : CMD ["/action.bash"]
 ---> Running in a3ffefd4499a
Removing intermediate container a3ffefd4499a
 ---> e326e790e7d4
Successfully built e326e790e7d4
Successfully tagged icinga/icingaweb2-builder:latest
+ docker run --rm -i -v /root/docker-icingaweb2/icingaweb2:/iw2src:ro -v /root/docker-icingaweb2:/bldctx:ro -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_MODE icinga/icingaweb2-builder bash
+ git -C /iw2src archive --prefix=iw2cp/icingaweb2/ HEAD
+ tar -xC /
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

```

how can solve this issue in ubuntu 20?

**Comment by johnfelipe** [comment]
Anyone?

**Comment by Al2Klimov** [comment]
What exactly are you doing?

**Comment by Al2Klimov** [comment]
Where does ./icingaweb2 come from?

**Comment by johnfelipe** [comment]
> Where does ./icingaweb2 come from?

in your readme

git clone https://github.com/Icinga/icingaweb2.git
#pushd icingaweb2
#git checkout v2.9.0
#popd

./build.bash ./icingaweb2

**Comment by lippserd** [comment]
> What exactly are you doing?

You have not answered the most important question. Anyway, I close here as it is most likely a problem with the location or content of the icingaweb git, as the error message shows.

**Comment by johnfelipe** [comment]
im trying to install your app for monitor and alerting vsphere vcenter enviroment, pls follow into this

https://github.com/Icinga/icingaweb2-module-vspheredb/issues/389#issuecomment-1238540474

**Comment by johnfelipe** [comment]
@lippserd any help pls in here....
