### ISSUE TITLE
Set PHP include path & `ICINGAWEB_CONFIGDIR` explicitly

### ISSUE THREAD

**Issue by yhabteab** [Icinga/docker-icingaweb2#98]
**Include path:** 
`ICINGAWEB_LIBRARY_PATH=/usr/share/icingaweb2/library`

```bash
.:/usr/share/php:$ICINGAWEB_LIBRARY_PATH:$ICINGAWEB_LIBRARY_PATH/vendor
```

**ConfigDir:** `/data/etc/icingaweb2`

**Comment by Al2Klimov** [comment]
Errm... where and what exactly for?

**Comment by yhabteab** [comment]
Well, tried to use our official Docker image for my GitHub actions to run module-specific unit tests, but Icinga Web 2 couldn't be loaded out of the box due to the include path not being set. It was necessary for me to set it manually during PHP setup, hence it would be better if this would have been set by this image itself. https://github.com/Icinga/icingaweb2-module-x509/pull/114/commits/8024886f67eece1a753632ba633902c629e6ab4d

**Comment by Al2Klimov** [comment]
> by this image itself

Apropos! Are you absolutely sure the entrypoint hasn't run (no lines like

https://github.com/Icinga/docker-icingaweb2/blob/e7632f02e5c9971bf53b793c254c097563ad0340/entrypoint/main.go#L268-L269

in logs)?

Also: Are you absolutely sure ICINGAWEB_CONFIGDIR is needed? AFAIK IW2 falls back to /etc/icingaweb2 which is /data/etc/icingaweb2 **if the entrypoint has run**.

Have you tried to run the entrypoint by yourself before PHPUnit so it inits everything?

Also, if GHA, I emphasise, GHA is doing some weird things, shall we not just do equally weird workarounds e.g. as you did?
